ThingFinder/Models/ViewModels/ThingViewModels.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace ThingFinder.Models.ViewModels
{

    public class RegisterThingViewModel
    {
        [Required]
        [MaxLength(70)]
        [Display(Name = "Opis")]
        public string Description { get; set; }

        [Required]
        [Display(Name = "Kategoria")]
        public int CategoryId { get; set; }

        [Required]
        [Display(Name = "Kolor")]
        public int ColorId { get; set; }
        [Required]
        [Display(Name = "Materiał")]
        public int StuffId { get; set; }
        

    }

    public class EditThingViewModel
    {
        public static int ThingId;
        [Required]
        [MaxLength(70)]
        [Display(Name = "Opis")]
        public string Description { get; set; }

        [Required]
        [Display(Name = "Kategoria")]
        public int CategoryId { get; set; }

        [Required]
        [Display(Name = "Status")]
        public int StatusId { get; set; }
    }

    public class SearchCodeThingViewModels
    {
        [Display(Name = "Kod")]
        public string Code { get; set; }
    }
}

ThingFinder/Controllers/PhotosController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ThingFinder.Models;
using ThingFinder.Models.ViewModels;

namespace ThingFinder.Controllers
{
    [Authorize]
    public class PhotosController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        [Authorize(Roles ="Admin")]
        // GET: Photos
        public ActionResult Index()
        {
            var photo = db.Photo.Include(p => p.Thing);
            return View(photo.ToList());
        }
        [Authorize(Roles = "Admin")]
        // GET: Photos/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Photo photo = db.Photo.Find(id);
            if (photo == null)
            {
                return HttpNotFound();
            }
            return View(photo);
        }
        [Authorize]
        // GET: Photos/Create
        public ActionResult Create(int id)
        {
            var isExists = db.Thing.Any(x => x.Id == id);
            if (!isExists)
                return HttpNotFound();
            if (User.Identity.Name != db.Thing.First(x => x.Id == id).User.Email)
                return new HttpStatusCodeResult(HttpStatusCode.Forbidden);
            AddPhotoViewModel.ThingId = id;
            //ViewBag.ThingId = new SelectList(db.Thing, "Id", "Code");
            return View(new AddPhotoViewModel());
        }

        // POST: Photos/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(HttpPostedFileBase file)
        {
            if (file == null || !file.ContentType.Contains("image"))
            {
                ViewBag.Error = "Nie zamieszczono pliku lub plik nie jest w formacie jpg, gif, png , jpeg";
                return View(new AddPhotoViewModel());
            }
            if (ModelState.IsValid)
            {
                //tworzenie ikony
                var icon = ThingFinder.Helpers.PhotoTools.ResizeImage(Image.FromStream(file.InputStream), 100, 100);
                db.Photo.Add(new Photo { Picture = ThingFinder.Helpers.PhotoTools.ImageToByte(Image.FromStream(file.InputStream)) , ThingId = AddPhotoViewModel.ThingId, Icon = ThingFinder.Helpers.PhotoTools.ImageToByte(icon)  });
                db.SaveChanges();
                return RedirectToAction("Index","Things");
            }

            //ViewBag.ThingId = new SelectList(db.Thing, "Id", "Code", photo.ThingId);
            return View(new AddPhotoViewModel());
        }

        // GET: Photos/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Photo photo = db.Photo.Find(id);
            if (photo == null)
            {
                return HttpNotFound();
            }
            ViewBag.ThingId = new SelectList(db.Thing, "Id", "Code", photo.ThingId);
            return View(photo);
        }

        // POST: Photos/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Icon,Picture,ThingId")] Photo photo)
        {
            if (ModelState.IsValid)
            {
                db.Entry(photo).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.ThingId = new SelectList(db.Thing, "Id", "Code", photo.ThingId);
            return View(photo);
        }

        // GET: Photos/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Photo photo = db.Photo.Find(id);
            if (photo == null)
            {
                return HttpNotFound();
            }
            return View(photo);
        }

        // POST: Photos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Photo photo = db.Photo.Find(id);
            db.Photo.Remove(photo);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        [Authorize]
        public ActionResult FindByPhoto()
        {
            return View();
        }
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult FindByPhoto(AddPhotoViewModel model ,HttpPostedFileBase file)
        {
            if (file == null || !file.ContentType.Contains("image"))
            {
                ViewBag.Error = "Nie zamieszczono pliku lub plik nie jest w formacie jpg, gif, png , jpeg";
                return View();
            }
            if (ModelState.IsValid)
            {
                //tworzenie ikony
                Image uploadImage = Image.FromStream(file.InputStream);
                List<ShowSimilars> similarImages = new List<ShowSimilars>();
                foreach (var subject in db.Photo)
                {
                    Image subjectPhoto = Helpers.PhotoTools.ConvertToImage(subject.Picture);
                   
                    var percentDiffrence = XnaFan.ImageComparison.ExtensionMethods.PercentageDifference(uploadImage, subjectPhoto,10);
                    var percentDiffrenceBhattacharyya = XnaFan.ImageComparison.ExtensionMethods.BhattacharyyaDifference(uploadImage, subjectPhoto);
                    if (percentDiffrence < 0.5 || model.isBhattacharyya)
                        similarImages.Add(new Models.ViewModels.ShowSimilars() { similar = ((1-percentDiffrence)*100).ToString() + "%", Photo = subject.Icon, similarBhattacharyya = percentDiffrenceBhattacharyya.ToString() });
                }
                if (similarImages.Count == 0)
                    return Content("Brak podobnych obrazków");
                if (model.isBhattacharyya)
                    similarImages = similarImages.OrderBy(x => x.similarBhattacharyya).Take(5).ToList();
                return View("ShowSimilars", similarImages);
            }

            //ViewBag.ThingId = new SelectList(db.Thing, "Id", "Code", photo.ThingId);
            return View(new AddPhotoViewModel());
        }
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ThingFinder/Controllers/ReportsController.cs
using Microsoft.AspNet.Identity.Owin;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ThingFinder.Models;
using ThingFinder.Models.ViewModels;
using ThingFinder.Validation;

namespace ThingFinder.Controllers
{
    public class ReportsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        private ApplicationUserManager _userManager;    
        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }
        // GET: Reports
        [Authorize]
        [RoleAuthorized(Message = "Nie jesteś autoryzowany. Proszę uzupełnić dane: Imie, Nazwisko, Telefon")]
        public ActionResult Index()
        {
            //na szybko
            var reports = db.Report.Where(x => x.Thing.User.Email == User.Identity.Name);
            return View(reports.ToList());
        }

        // GET: Reports/Details/5
        [Authorize]
        [RoleAuthorized(Message = "Nie jesteś autoryzowany. Proszę uzupełnić dane: Imie, Nazwisko, Telefon")]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Report report = db.Report.Find(id);
            if (report == null)
            {
                return HttpNotFound();
            }
            return View(report);
        }

        public ActionResult Found(string code)
        {
            if (db.Thing.Any(x => x.Code == code))
            {
                // await UserManager.SendEmailAsync(db.Thing.First(x => x.Code == code).UserId, "Znalazeiono Przedmiot", "Przedmiot o kodzie " + code + "został znaleziony. Szczegóły znajdują się reporcie");
                //return Content("Gratulacje znalazco");
                AddReportViewModel reportViewModel = new AddReportViewModel();
                AddReportViewModel.ThingId = db.Thing.First(x => x.Code == code).Id;
                AddReportViewModel.OwnerId = db.Thing.First(x => x.Code == code).UserId;
                AddReportViewModel.codeThing = code;
                if (Request.IsAuthenticated)
                    reportViewModel.Founder = User.Identity.Name;
                return View(reportViewModel);
            }

            else return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async System.Threading.Tasks.Task<ActionResult> Found([Bind(Include = "Id,Longitude,Latitude,Description,DateOfFound,DateOfNotification,Founder,UserId,ThingId")] AddReportViewModel report)
        {
            if (ModelState.IsValid)
            {
                Report rep = new Report() { Longitude = report.Longitude, Latitude = report.Latitude, DateOfNotification = System.DateTime.Now, DateOfFound = report.DateOfFound, Description = report.Description, ThingId = AddReportViewModel.ThingId, Founder = report.Founder };
                string codeThing="";
                string UserId="";
              
                db.Report.Add(rep);
                try
                {
                    db.SaveChanges();
                    //UserId = db.Thing.First(x => x.Code == rep.Thing.Code).UserId; codeThing = rep.Thing.Code;       //nie dziala bo nie wiem dlaczego
                    UserId = AddReportViewModel.OwnerId; codeThing = AddReportViewModel.codeThing;
                }
                catch (Exception ex)
                {
                    ex.ToString();
                }

                await UserManager.SendEmailAsync(UserId, "Znaleziono Przedmiot", "Przedmiot o kodzie " + codeThing + " został znaleziony. Szczegóły znajdują się raporcie");
                return RedirectToAction("Index", "Home");
            }
            return View(report);
        }

        //// POST: Reports/Create
        //// To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        //// more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult Create([Bind(Include = "Id,Longitude,Latitude,Description,DateOfFound,DateOfNotification,Founder,UserId,ThingId")] Report report)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        db.Reports.Add(report);
        //        db.SaveChanges();
        //        return RedirectToAction("Index");
        //    }

        //    ViewBag.ThingId = new SelectList(db.Things, "Id", "Code", report.ThingId);
        //    ViewBag.UserId = new SelectList(db.ApplicationUsers, "Id", "Name", report.UserId);
        //    return View(report);
        //}

        //// GET: Reports/Edit/5
        //public ActionResult Edit(int? id)
        //{
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    Report report = db.Reports.Find(id);
        //    if (report == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    ViewBag.ThingId = new SelectList(db.Things, "Id", "Code", report.ThingId);
        //    ViewBag.UserId = new SelectList(db.ApplicationUsers, "Id", "Name", report.UserId);
        //    return View(report);
        //}

        //// POST: Reports/Edit/5
        //// To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        //// more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult Edit([Bind(Include = "Id,Longitude,Latitude,Description,DateOfFound,DateOfNotification,Founder,UserId,ThingId")] Report report)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        db.Entry(report).State = EntityState.Modified;
        //        db.SaveChanges();
        //        return RedirectToAction("Index");
        //    }
        //    ViewBag.ThingId = new SelectList(db.Things, "Id", "Code", report.ThingId);
        //    ViewBag.UserId = new SelectList(db.ApplicationUsers, "Id", "Name", report.UserId);
        //    return View(report);
        //}

        //// GET: Reports/Delete/5
        //public ActionResult Delete(int? id)
        //{
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    Report report = db.Reports.Find(id);
        //    if (report == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    return View(report);
        //}

        //// POST: Reports/Delete/5
        //[HttpPost, ActionName("Delete")]
        //[ValidateAntiForgeryToken]
        //public ActionResult DeleteConfirmed(int id)
        //{
        //    Report report = db.Reports.Find(id);
        //    db.Reports.Remove(report);
        //    db.SaveChanges();
        //    return RedirectToAction("Index");
        //}

        //protected override void Dispose(bool disposing)
        //{
        //    if (disposing)
        //    {
        //        db.Dispose();
        //    }
        //    base.Dispose(disposing);
        //}
    }
}

ThingFinder/Views/Things/AllThings.cshtml
@model IEnumerable<ThingFinder.Models.Thing>

@{
    ViewBag.Title = "Index";
}

<h2>Admin przedmioty</h2>

<table class="table">
    <tr>
        <th>
            @*@Html.DisplayNameFor(model => model.Photo.Picture)*@
            Ikona
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Status.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Code)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DateRegistration)
        </th>

        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @{
                    @*if (item.Photo.Count != 0)
                        {
                            byte[] photo = item.Photo.First(x => x.ThingId == item.Id).Icon;
                            string imageSrc = null;
                            string imageAlt = "Image" + item.Id.ToString();
                            if (photo != null)
                            {
                                MemoryStream ms = new MemoryStream();

                                string imageBase64 = Convert.ToBase64String(ms.ToArray());
                                imageSrc = string.Format("data:image/jpeg;base64,{0}", imageBase64);
                                <img src="@imageSrc" alt="@imageAlt" />
                            }
                        }*@
                if (item.Photo.Count > 0)
                {
                    var photo = item.Photo.First(x => x.ThingId == item.Id).Icon;

                    <img src="data:image/png;base64,@Convert.ToBase64String(photo)"
                         alt="Image" />
                }
                else
                {
                    <img src="@Url.Content("~/Content/images/announcements.png")" height="100" width="100" alt="@item.Code" />
                }


                }
            </td>



            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Status.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Code)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DateRegistration)
            </td>

            <td>
                @Html.ActionLink("Edytuj", "Edit", new { id = item.Id }, new { @class = "btn btn-default btn-lg" })
                @Html.ActionLink("Szczegóły", "Details", new { id = item.Id }, new { @class = "btn btn-default btn-lg" })
                @Html.ActionLink("Usuń", "Delete", new { id = item.Id }, new { @class = "btn btn-danger btn-lg" })
                @if (item.Status.Name == "Zgubiony")
                {
                    @Html.ActionLink("Stwórz Ogłoszenie", "AddAnnoucement", "Announcements", new { thingId = item.Id }, new { @class = "btn btn-warning btn-lg" })
                }
                @if (item.Photo.Count == 0)
                {
                    @Html.ActionLink("Dodaj Zdjęcie", "Create", "Photos", new { id = item.Id }, new { @class = "btn btn-warning btn-lg" })
                }
                @Html.ActionLink("Generuj naklejke", "GenerateSticker", new { code = item.Code }, new { @class = "btn btn-success btn-lg" })

            </td>
        </tr>
                    }

</table>


ThingFinder/Views/Things/Create.cshtml
@model ThingFinder.Models.ViewModels.RegisterThingViewModel

@{
    ViewBag.Title = "Create";
}

<h2>Dodaj przedmiot</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            @Html.LabelFor(model => model.CategoryId, "Kategoria", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CategoryId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CategoryId, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.ColorId, "Kolor", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ColorId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ColorId, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.StuffId, "Materiał", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("StuffId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.StuffId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Dodaj" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Powrót do moich przedmiotów", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ThingFinder/Views/Things/Delete.cshtml
@model ThingFinder.Models.Thing

@{
    ViewBag.Title = "Delete";
}

<h2>Usuwanie</h2>

<h3>Czy jesteś pewnien usunięcia przedmiotu?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Filter.Color.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Filter.Color.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Filter.Stuff.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Filter.Stuff.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Status.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Status.Name)
        </dd>


        <dt>
            @Html.DisplayNameFor(model => model.Code)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Code)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DateRegistration)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DateRegistration)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Usuń" class="btn btn-danger" /> |
            @Html.ActionLink("Powrót do listy", "Index",null , new { @class = "btn btn-default" })
        </div>
    }
</div>

ThingFinder/Views/Things/Details.cshtml
@model ThingFinder.Models.Thing

@{
    ViewBag.Title = "Details";
}

<h2>Szczegóły</h2>

<div>
    <h4>@Model.Description</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Ikona
        </dt>
        <dd>
            @if (Model.Photo.Count > 0)
            {
            var photo = Model.Photo.First(x => x.ThingId == Model.Id).Icon;

            <img src="data:image/png;base64,@Convert.ToBase64String(photo)"
                 alt="Image" />
            }
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Filter.Color.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Filter.Color.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Filter.Stuff.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Filter.Stuff.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Status.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Status.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Code)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Code)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DateRegistration)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DateRegistration)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edytuj", "Edit", new { id = Model.Id }, new { @class = "btn btn-default" }) |
    @Html.ActionLink("Powrót do listy", "Index", null, new { @class = "btn btn-default" })
</p>

ThingFinder/Views/Things/Index.cshtml
@model IEnumerable<ThingFinder.Models.Thing>

@{
    ViewBag.Title = "Index";
}

<h2>Moje przedmioty</h2>

<p>
    @Html.ActionLink("Dodaj Przedmiot", "Create",null ,new { @class = "btn btn-success btn-lg" })
</p>
<table class="table">
    <tr>
        <th>
            @*@Html.DisplayNameFor(model => model.Photo.Picture)*@ 
            Ikona
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Status.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Code)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DateRegistration)
        </th>

        <th></th>
    </tr>

@foreach (var item in Model)
{
    <tr>
        <td>
            @{
                @*if (item.Photo.Count != 0)
                {
                    byte[] photo = item.Photo.First(x => x.ThingId == item.Id).Icon;
                    string imageSrc = null;
                    string imageAlt = "Image" + item.Id.ToString();
                    if (photo != null)
                    {
                        MemoryStream ms = new MemoryStream();

                        string imageBase64 = Convert.ToBase64String(ms.ToArray());
                        imageSrc = string.Format("data:image/jpeg;base64,{0}", imageBase64);
                        <img src="@imageSrc" alt="@imageAlt" />
                    }
                }*@
            if (item.Photo.Count > 0)
            {
                var photo = item.Photo.First(x => x.ThingId == item.Id).Icon;

                <img src="data:image/png;base64,@Convert.ToBase64String(photo)"
                     alt="Image" />
            }
            else
            {
                <img src="@Url.Content("~/Content/images/announcements.png")" height="100" width="100" alt="@item.Code" />
            }


}
        </td>



        <td>
            @Html.DisplayFor(modelItem => item.Description)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Status.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Code)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DateRegistration)
        </td>

        <td>
            @Html.ActionLink("Edytuj", "Edit", new { id = item.Id }, new { @class = "btn btn-default btn-lg" })
            @Html.ActionLink("Szczegóły", "Details", new { id = item.Id }, new { @class = "btn btn-default btn-lg" })
            @Html.ActionLink("Usuń", "Delete", new { id = item.Id }, new { @class = "btn btn-danger btn-lg" })
            @if (item.Status.Name == "Zgubiony")
            {
                @Html.ActionLink("Stwórz Ogłoszenie", "AddAnnoucement", "Announcements", new { thingId = item.Id }, new { @class = "btn btn-warning btn-lg" })
            }
            @if (item.Photo.Count == 0)
            {
                @Html.ActionLink("Dodaj Zdjęcie", "Create", "Photos", new { id = item.Id }, new { @class = "btn btn-warning btn-lg" })
            }
            @Html.ActionLink("Generuj naklejke", "GenerateSticker", new { code = item.Code }, new { @class = "btn btn-success btn-lg" })

        </td>
    </tr>
}

</table>

ThingFinder/Views/Things/_SearchCodeThing.cshtml
@model ThingFinder.Models.ViewModels.SearchCodeThingViewModels

@using (Html.BeginForm("Found", "Reports", FormMethod.Get))
{
    <div class="form-horizontal margin-top-20">

        <div class="form-group">
            @Html.LabelFor(model => model.Code, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10 nopadding">
                @Html.EditorFor(model => model.Code, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Code, "", new { @class = "text-danger" })
                <input type="submit" value="Wyszukaj" class="btn btn-default btn-block" />
            </div>
        </div>

    </div>
}