ThingFinder/Controllers/AnnouncementsController.cs
using Microsoft.AspNet.Identity.Owin;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.Entity.Validation;
using System.Device.Location;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ThingFinder.Models;
using ThingFinder.Models.ViewModels;
using ThingFinder.Validation;

namespace ThingFinder.Controllers
{
    public class AnnouncementsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        #region UserMananger
        private ApplicationUserManager _userManager;
        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }
        #endregion UserManager

        [ChildActionOnly]
        public ActionResult SearchAnnouncements(string id = "")
        {
            if (id.Equals("Code"))
            {
                return PartialView("~/Views/Things/_SearchCodeThing.cshtml", new SearchCodeThingViewModels { Code = null });
            }
            else if (id.Equals("Photo"))
            {
                return PartialView("~/Views/Photos/_SearchPhoto.cshtml");
            }

            var categoryOptions = db.Category.Select(c => new SelectListItem { Text = c.Name, Value = c.Id.ToString() }).ToList();
            var typeOptions = db.Type.Select(t => new CheckBoxSearch { Text = t.Name, Value = t.Id }).ToList();

            return PartialView("_SearchAnnouncements", new SearchAnnouncementsViewModels { Categorys = categoryOptions, Types = typeOptions });
        }

        private bool CheckLocation(GeoCoordinate sCoord, GeoCoordinate eCoord, double range)
        {
            double distance = sCoord.GetDistanceTo(eCoord);
            if (range < distance)
                return false;
            return true;
        }

        // GET: Announcements
        public ActionResult Index(string keyWords = null, string longitude = null, string latitude = null, string range = null,
            string categoryId = null)
        {
            List<Announcement> announcement;

            if (!string.IsNullOrEmpty(keyWords))
            {
                announcement = db.Announcement.Where(a => a.KeyWords.Contains(keyWords) && (a.Status.Name == "Znaleziony" || a.Status.Name == "Zgubiony")).ToList();
            }
            else
            {
                announcement = db.Announcement.Where(a => a.Status.Name == "Znaleziony" || a.Status.Name == "Zgubiony").ToList();
            }

            if (!string.IsNullOrEmpty(categoryId))
            {
                announcement.RemoveAll(x => x.CategoryId != Convert.ToInt16(categoryId));
            }

            if (!string.IsNullOrEmpty(longitude) && !string.IsNullOrEmpty(latitude) && !string.IsNullOrEmpty(range))
            {
                double lati = Convert.ToDouble(latitude);
                double longi = Convert.ToDouble(longitude);
                double ra = Convert.ToDouble(range);
                var sCoord = new GeoCoordinate(lati, longi);

                announcement.RemoveAll(x => !CheckLocation(sCoord, 
                    new GeoCoordinate(Convert.ToDouble(x.Latitude), Convert.ToDouble(x.Longitude)),
                    ra + Convert.ToDouble(x.Range)));
            }

            return View(announcement);
        }

        [Authorize]
        [RoleAuthorized(Message = "Nie jesteś autoryzowany. Proszę uzupełnić dane: Imie, Nazwisko, Telefon.")]
        public ActionResult MyAnnoucements()
        {
            var myAnnouncement = db.Announcement.Where(a => a.Status.Name == "Znaleziony" || a.Status.Name == "Zgubiony").Where(u => u.User.Email == User.Identity.Name);
            return View(myAnnouncement.ToList());
        }

        [Authorize(Roles ="Admin")]
        public ActionResult AllAnnoucements()
        {
            var announcement = db.Announcement.Include(a => a.Category).Include(a => a.Status).Include(a => a.Type);
            return View(announcement.ToList());
        }

        [ChildActionOnly]
        public ActionResult SelectedTwoLast()
        {
            var announcement = db.Announcement.Where(a => a.Status.Name == "Znaleziony" || a.Status.Name == "Zgubiony").OrderByDescending(a => a.DateOfAnnouncement).Take(2);
            return PartialView("_Announcement", announcement.ToList());
        }

        // GET: Announcements/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Announcement announcement = db.Announcement.Find(id);
            if (announcement == null)
            {
                return HttpNotFound();
            }
            return View(announcement);
        }



        // GET: Announcements/Create
        [Authorize]
        [RoleAuthorized(Message = "Nie jesteś autoryzowany. Proszę uzupełnić dane: Imie, Nazwisko, Telefon")]
        public ActionResult Create()
        {

            var categoryOptions = db.Category.Select(c => new SelectListItem { Text = c.Name, Value = c.Id.ToString() }).ToList();
            var statusOptions = db.Status.Select(s => new SelectListItem { Text = s.Name, Value = s.Id.ToString() }).ToList();
            var typeOptions = db.Type.Select(t => new SelectListItem { Text = t.Name, Value = t.Id.ToString() }).ToList();

            return View(new AddAnnouncementsViewModels { Categorys = categoryOptions, Status = statusOptions, Types = typeOptions });
        }

        // POST: Announcements/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(AddAnnouncementsViewModels model)
        {

            if (ModelState.IsValid)
            {
                var announcement = new Announcement
                {
                    Description = model.Description,
                    Latitude = model.Latitude,
                    Longitude = model.Longitude,
                    KeyWords = model.KeyWords,
                    DateOfAnnouncement = model.DateOfAnnouncement,
                    Range = model.Range,
                    TypeId = model.TypeId,
                    StatusId = model.StatusId,
                    CategoryId = model.CategoryId,
                    UserId = db.Users.First(x => x.Email == User.Identity.Name).Id
                };

                db.Announcement.Add(announcement);

                try
                {
                    db.SaveChanges();
                }
                catch (Exception ex)
                {
                    throw;
                }

                return RedirectToAction("Index");
            }

            var categoryOptions = db.Category.Select(c => new SelectListItem { Text = c.Name, Value = c.Id.ToString() }).ToList();
            var statusOptions = db.Status.Select(s => new SelectListItem { Text = s.Name, Value = s.Id.ToString() }).ToList();
            var typeOptions = db.Type.Select(t => new SelectListItem { Text = t.Name, Value = t.Id.ToString() }).ToList();

            return View(new AddAnnouncementsViewModels { Categorys = categoryOptions, Status = statusOptions, Types = typeOptions });
        }

        #region AddAnnouncementThroughThing
        [Authorize]
        public ActionResult AddAnnoucement(int thingId)
        {
            //Czy przedmiot istnieje i nalezy do uzytkownika
            if (!db.Thing.Any(x => x.Id == thingId) && db.Thing.First(z => z.Id == thingId).User.Email != User.Identity.Name)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            Thing thing = db.Thing.First(x => x.Id == thingId);

            var categoryOptions = db.Category.Select(c => new SelectListItem { Text = c.Name, Value = c.Id.ToString() }).ToList();
            var statusOptions = db.Status.Select(s => new SelectListItem { Text = s.Name, Value = s.Id.ToString() }).ToList();
            var typeOptions = db.Type.Select(t => new SelectListItem { Text = t.Name, Value = t.Id.ToString() }).ToList();
            AddAnnouncementThing announcement = new AddAnnouncementThing()
            {
                Description = thing.Description,
                StatusId = thing.StatusId,
                TypeId = 1,
                CategoryId = thing.CategoryId,
                Categorys = categoryOptions,
                Status = statusOptions,
                Types = typeOptions
            }; 
            return View(announcement);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AddAnnoucement(AddAnnouncementThing model)
        {

            if (ModelState.IsValid)
            {
                var announcement = new Announcement
                {
                    Description = model.Description,
                    Latitude = model.Latitude,
                    Longitude = model.Longitude,
                    KeyWords = model.KeyWords,
                    DateOfAnnouncement = model.DateOfAnnouncement,
                    Range = model.Range,
                    TypeId = model.TypeId,
                    StatusId = model.StatusId,
                    CategoryId = model.CategoryId,
                    UserId = db.Users.First(x => x.Email == User.Identity.Name).Id
                };

                db.Announcement.Add(announcement);


ThingFinder/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ThingFinder.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index(string id = "")
        {
            ViewBag.Id = id;
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

ThingFinder/Views/Home/About.cshtml
@{
    ViewBag.Title = "O nas";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Jest to strona wspomagająca poszukiwanie rzeczy zaguibionych. Praca licencjacka</p>

ThingFinder/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

ThingFinder/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";

    var act1 = "";
    var act2 = "";
    var act3 = "";

    var height = "";

    if (ViewBag.Id == "Code")
    {
        height = "code";
        act2 = "act";
    } else if (ViewBag.Id == "Photo")
    {
        act3 = "act";
    } else
    {
        act1 = "act";
    }
}

<div class="banner"></div>

<div class="container btn-search">
    <div class="row">
        <div class="col-xs-12 text-right text-uppercase" style="margin-top: -63px;">
            <a href="@Url.Action("Index", "Home", new { id = "" })" class="btn btn-lg @act1">
                <span class="glyphicon glyphicon-search" aria-hidden="true"></span>
                <p>Wyszukiwanie</p>
            </a>
            <a href="@Url.Action("Index", "Home", new { id = "Code" })" class="btn btn-lg @act2">
                <span class="glyphicon" >#</span>
                <p>Kod przedmiotu</p>
            </a>
            <a href="@Url.Action("Index", "Home", new { id = "Photo" })" class="btn btn-lg  @act3">
                <span class="glyphicon glyphicon-camera" aria-hidden="true"></span>
                <p>Po zdjęciu</p>
            </a>
        </div>
    </div>
</div>

<div class="col-xs-offset-2 col-xs-10" style="padding: 0;">
    <div class="modal-trapeze search @height">
        <div class="col-xs-10">
            @Html.Action("SearchAnnouncements", "Announcements")
        </div>
    </div>
</div>

<div class="container">

    @Html.Action("SelectedTwoLast", "Announcements")

    <div class="row">
        <div class="col-xs-12 text-center text-uppercase margin-top-40">
            <div class="belt"></div>
            <div class="background">
                <div class="model-parallelogram-reflection btn btn-default">
                    @Html.ActionLink("Więcej", "Index", "Announcements", null, new { @class = "btn btn-default btn-lg" })
                </div>
            </div>
        </div>
    </div>
</div>

@section Scripts {

    @Scripts.Render("~/bundles/map")

    <script type="text/javascript">

        function initMap() {
            maps.setRadius(NaN);
            maps.setLocation(true);
            maps.init();
        }

        jQuery.validator.methods["date"] = function (value, element) {
            return this.optional(element) || /^\d{2}[-]\d{2}[-]\d{4}$/.test(value);
        }

        jQuery.validator.methods["number"] = function (value, element) {
            return this.optional(element) || /^(?:-?\d+|-?\d{1,3}(?:,\d{3})+)?(?:\.\d+)?(?:\,\d+)?$/.test(value);
        }

    </script>

    <script async defer
            src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDnXkUYDhTQVAdtI4f3fF2mYUT6Z0B-jRw&callback=initMap">
    </script>
}
