ThingFinder/Controllers/ThingsController.cs
using Microsoft.AspNet.Identity.Owin;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Drawing;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ThingFinder.Models;
using ThingFinder.Models.ViewModels;
using ThingFinder.Validation;

namespace ThingFinder.Controllers
{
    [Authorize]
    [RoleAuthorized(Message = "Nie jesteś autoryzowany. Proszę uzupełnić dane: Imie, Nazwisko, Telefon")]
    public class ThingsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        private string regExp = "[a-zA-Z]{9}";


        // GET: Things
        public ActionResult Index()
        {
            string UserId = db.Users.First(x => x.Email == User.Identity.Name).Id;
            var thing = db.Thing.Include(t => t.Filter).Include(t => t.Status).Include(t => t.User).Where(x => x.User.Id == UserId);
            return View(thing.ToList());
        }

        [Authorize(Roles = "Admin")]
        public ActionResult AllThings()
        {
            var thing = db.Thing.Include(t => t.Filter).Include(t => t.Status).Include(t => t.User);
            return View(thing.ToList());
        }

        // GET: Things/Details/5
        public ActionResult Details(int? id)
        {
      
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Thing thing = db.Thing.Find(id);
            if (thing == null)
            {
                return HttpNotFound();
            }
            return View(thing);
        }

        // GET: Things/Create
        public ActionResult Create()
        {
            ViewBag.ColorId = new SelectList(db.Color, "Id", "Name");
            ViewBag.StuffId = new SelectList(db.Stuff, "Id", "Name");
            ViewBag.CategoryId = new SelectList(db.Category, "Id", "Name");

            if (!db.Users.First(x => x.Email == User.Identity.Name).CanAddThing)
            {
                TempData["MessageFromMyAttribute"] = "Proszę uzupełnić dane: Imie, Nazwisko, Telefon";
                return RedirectToAction("Settings", "Manage");
            }
              

            return View();
        }

        // POST: Things/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        public ActionResult Create(RegisterThingViewModel registerdThing)
        {
            Fare.Xeger xeger = new Fare.Xeger(regExp);
            string Code = xeger.Generate();
            int exists = db.Thing.Where(x => x.Code == Code).ToList().Count;
            while (exists > 0)
            {
                Code = xeger.Generate();
                exists = db.Thing.Where(x => x.Code == Code).ToList().Count;
            }
            string UserId = UserId = db.Users.First(x => x.Email == User.Identity.Name).Id;
            int StatusId = db.Status.First(x => x.Name == "OK").Id;
            Thing thing = new Thing(Code, UserId, StatusId,registerdThing.ColorId,registerdThing.CategoryId,registerdThing.Description,registerdThing.StuffId);
            if (ModelState.IsValid)
            {
                db.Thing.Add(thing);
                try
                {
                    db.SaveChanges();

                }
                catch (Exception ex)
                {

                    throw;
                }
                
                return RedirectToAction("Index");
            }

            ViewBag.ColorId = new SelectList(db.Color, "Id", "Name");
            ViewBag.StuffId = new SelectList(db.Stuff, "Id", "Name");
            ViewBag.CategoryId = new SelectList(db.Category, "Id", "Name");

            return View();
        }

        // GET: Things/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Thing thing = db.Thing.Find(id);
            if (thing == null)
            {
                return HttpNotFound();
            }
           // ViewBag.FilterId = new SelectList(db.Filter, "Id", "Id", thing.FilterId);
            ViewBag.StatusId = new SelectList(db.Status, "Id", "Name", thing.StatusId);
            ViewBag.CategoryId = new SelectList(db.Category, "Id", "Name");
            EditThingViewModel editthing = new EditThingViewModel();
            EditThingViewModel.ThingId = thing.Id;
            editthing.StatusId = thing.StatusId;
            editthing.CategoryId = thing.CategoryId;
            editthing.Description = thing.Description;
            return View(editthing);
        }

        // POST: Things/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(EditThingViewModel editthing)
        {
            if (ModelState.IsValid)
            {
                Thing thing = db.Thing.First(x => x.Id == EditThingViewModel.ThingId);
                thing.Description = editthing.Description;
                thing.CategoryId = editthing.CategoryId;
                thing.StatusId = editthing.StatusId;
                db.Entry(thing).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
           // ViewBag.FilterId = new SelectList(db.Filter, "Id", "Id", thing.FilterId);
            ViewBag.StatusId = new SelectList(db.Status, "Id", "Name", editthing.StatusId);
            ViewBag.CategoryId = new SelectList(db.Category, "Id", "Name");
            return View(editthing);
        }

        // GET: Things/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Thing thing = db.Thing.Find(id);
            if (thing == null)
            {
                return HttpNotFound();
            }
            return View(thing);
        }

        // POST: Things/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Thing thing = db.Thing.Find(id);
            db.Thing.Remove(thing);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult GenerateSticker(string code)
        {
            string userId = db.Users.First(x => x.Email == User.Identity.Name).Id;
            if (!db.Thing.Any( x=> x.Code == code))
                return new HttpStatusCodeResult(HttpStatusCode.Forbidden);
            Thing thing = db.Thing.First(x => x.Code == code);
            if (userId != thing.UserId)
                return new HttpStatusCodeResult(HttpStatusCode.Forbidden);

            Image sticker = Helpers.QRCodeMaker.GenerateSticker(code,Url.Action("Found","Reports",new { code = thing.Code },Request.Url.Scheme));
            var cd = new System.Net.Mime.ContentDisposition
            {
                FileName = code+".bmp",

                Inline = false,
            };
            Response.AppendHeader("Content-Disposition", cd.ToString());
            return File(ThingFinder.Helpers.PhotoTools.ImageToByte(sticker), "image/bmp");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

    }
}

ThingFinder/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - ThingFinder</title>
    @Styles.Render("~/Content/css")
    @Styles.Render("https://fonts.googleapis.com/css?family=Open+Sans")
    @Styles.Render("http://pl.allfont.net/allfont.css?fonts=agency-fb-bold")
    @Scripts.Render("~/bundles/modernizr")
    <meta name="description" content="The description of my page" />
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a href="@Url.Action("Index", "Home")" title="index" class="navbar-brand">
                    <img src=@Url.Content("~/Content/images/logo-thingfinder.png") alt="logo" />
                </a>
            </div>
            <div class="navbar-collapse collapse">
                <div class="nav navbar-nav navbar-right menu-language">
                    @Html.ActionLink("PL", "Index", "Home", routeValues: null, htmlAttributes: new { @class = "activite" })
                    <spam>/</spam>
                    @Html.ActionLink("EN", "Index", "Home")
                </div>
                @Html.Partial("_LoginPartial")
                <ul class="nav navbar-nav navbar-right padding-right-10">
                    <li>@Html.ActionLink("Strona główna", "Index", "Home")</li>
                    @*@if (Request.IsAuthenticated)
                    {
                        <li>@Html.ActionLink("Moje Przedmioty","Index","Things")</li>
                    }
                    <li>@Html.ActionLink("Ogłoszenia","Index","Announcements")</li>*@
                    <li>@Html.ActionLink("O nas", "About", "Home")</li>
                    <li>@Html.ActionLink("Kontakt", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    @Html.Partial("_RegisterPartial")
    <div class="container-frame">
        @RenderBody()
        <footer class="text-center">
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/jqueryval")
    @RenderSection("scripts", required: false)
</body>
</html>

ThingFinder/Views/Shared/_RegisterPartial.cshtml
@using Microsoft.AspNet.Identity

@if (!Request.IsAuthenticated)
{
    <div id="register" class="modal fade" role="dialog">
        <div class="modal-dialog">

            <!-- Modal content-->
            <div class="modal-content">
                <div class="modal-header">
                    <div class="container-fluid modal-trapeze col-xs-offset-3 col-xs-9">
                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                        <h4 class="modal-title text-uppercase">Rejstracja</h4>
                    </div>
                </div>
                <div class="modal-body">
                    @{ Html.RenderPartial("~/Views/Account/_Register.cshtml", new ThingFinder.Models.RegisterViewModel()); }
                </div>
            </div>

        </div>
    </div>
}